[package]
name = "real_world_rust"
version = "0.1.0"
authors = ["Wei Ning <macgnw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
