pub mod boxed;
pub mod clone_on_write;
pub mod copy_clone;
pub mod global_unsafe;
pub mod internal_mutability_pattern;
pub mod lazy_static_objects;
pub mod lifetime;
pub mod ownership_and_borrowing;
pub mod rc;
pub mod ref_counter;
pub mod refcell_interior_mut;
pub mod smart_pointers;
pub mod static_data;
pub mod std_mem;
mod ownership_and_copying;
